DANGEROUS_PERMISSIONS = {
    "android.permission.READ_CONTACTS": "Read all contacts on the device",
    "android.permission.WRITE_CONTACTS": "Modify or delete contacts",
    "android.permission.READ_CALL_LOG": "Access call history",
    "android.permission.WRITE_CALL_LOG": "Modify call history",
    "android.permission.READ_SMS": "Read text messages",
    "android.permission.RECEIVE_SMS": "Intercept incoming SMS",
    "android.permission.SEND_SMS": "Send SMS (may cost money)",
    "android.permission.RECORD_AUDIO": "Access the microphone",
    "android.permission.CAMERA": "Access the camera",
    "android.permission.ACCESS_FINE_LOCATION": "Precise GPS location",
    "android.permission.ACCESS_COARSE_LOCATION": "Approximate location",
    "android.permission.ACCESS_BACKGROUND_LOCATION": "Location even when app is closed",
    "android.permission.READ_EXTERNAL_STORAGE": "Read all files on device",
    "android.permission.WRITE_EXTERNAL_STORAGE": "Write files to device storage",
    "android.permission.GET_ACCOUNTS": "Access accounts linked to device",
    "android.permission.USE_BIOMETRIC": "Access fingerprint/face unlock",
    "android.permission.PROCESS_OUTGOING_CALLS": "Monitor or redirect phone calls",
    "android.permission.READ_PHONE_STATE": "Access device ID, phone number",
    "android.permission.INSTALL_PACKAGES": "Silently install other apps",
    "android.permission.REQUEST_INSTALL_PACKAGES": "Request to install APKs",
}

SUSPICIOUS_PERMISSIONS = {
    "android.permission.RECEIVE_BOOT_COMPLETED": "Starts automatically at device boot",
    "android.permission.FOREGROUND_SERVICE": "Runs a persistent background service",
    "android.permission.SYSTEM_ALERT_WINDOW": "Draw over other apps (overlay)",
    "android.permission.CHANGE_NETWORK_STATE": "Modify network connectivity",
    "android.permission.DISABLE_KEYGUARD": "Dismiss the lockscreen",
}